version: '3.1'

services:
  
  frontend:
    build: 
      dockerfile: Dockerfile.frontend
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/src

  backend:
    build: 
      dockerfile: Dockerfile.backend
      context: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - NODE_ENV=development
    volumes:
      - ./server/routes:/routes
      - ./server/views:/views
    