version: '3.1'

services:

  web:
    build: 
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./routes:/routes
      - ./views:/views
    depends_on:
      - mongo
      - postgres
  
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db

  mongo:
    image: mongo:3.6.6-jessie
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=db